### ISSUE TITLE
enhancement - decouple examples into separate repo

### ISSUE THREAD

**Issue by johndpope** [SwiftGFX/SwiftBGFX#5]
currently to build mac os project 
the readme appears out of date.

there's no +
cd SwiftBGFX/3rdparty/bgfx+

there also appears to be no Math
cd SwiftBGFX/3rdparty/Math

when I run make macos - it all compiles fine.

// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

```
import PackageDescription

let package = Package(
    name: "examples",
    dependencies: [
        .package(url: "https://github.com/SwiftGFX/SwiftBGFX", .upToNextMinor(from: "2.0.0")),
        .package(url: "https://github.com/SwiftGFX/SwiftMath", .upToNextMinor(from: "3.0.0")),
        // Dependencies declare other packages that this package depends on.
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "examples",
            dependencies: ["SwiftMath","SwiftBGFX"]),
    ]
)

```

UPDATe
I just spent 20 mins faffing around trying to get the samples working - but all I actually wanted was to see the code being used in another project - consider adding Fiber2D on homepage.
https://github.com/s1ddok/Fiber2D

**Comment by s1ddok** [comment]
to be honest examples are not supported for quite a long now. 

I've just updated repo to latest BGFX API and Swift 4. Example are likely to be removed out of the repo

**Comment by johndpope** [comment]
thx
